export const BLINDFOLD_CARDS = [
  {
    "id": "blindfold_001",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Twee Minuten Verrassing",
    "text": "Draag twee minuten een blinddoek. De ander kiest uit zachte aanrakingen, kusjes, knuffelen of plagen binnen jullie afgesproken grenzen.",
    "level": 3,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "body-contact"
    ],
    "safetyNote": "WALIBI betekent direct stoppen."
  },
  {
    "id": "blindfold_002",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Raad de Smaak",
    "text": "Proef geblinddoekt iets kleins en raad wat het is.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "food"
    ],
    "safetyNote": "Blijf rechtop zitten en gebruik geen harde of verstikkingsgevoelige snacks."
  },
  {
    "id": "blindfold_003",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Drie Kusplekken",
    "text": "De ander kust je geblinddoekt op drie verschillende, afgesproken plekken. Raad waar.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "kissing"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_004",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Raad de Aanraking",
    "text": "Raad welk lichaamsdeel de ander zachtjes aanraakt.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "touch"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_005",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Make-upkwast Challenge",
    "text": "Blijf geblinddoekt. De ander mag met een zachte make-upkwast langzaam langs je lichaam strijken en je speels kietelen op afgesproken plekken.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "makeup"
    ],
    "safetyNote": null
  },
  {
    "id": "blindfold_006",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Raad het Voorwerp",
    "text": "Eén speler is geblinddoekt. De ander geeft één veilig voorwerp in de hand. Raad wat het is.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "object"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_007",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Dertig Seconden Kietelen",
    "text": "Je mag de ander dertig seconden geblinddoekt kietelen op afgesproken plekken. Stopwoord: WALIBI.",
    "level": 3,
    "timerSeconds": 30,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "tickling"
    ],
    "safetyNote": "Stop onmiddellijk bij WALIBI."
  },
  {
    "id": "blindfold_008",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Mysterie-accessoire",
    "text": "De ander zet je geblinddoekt een accessoire op. Raad wat het is.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "dressup"
    ],
    "safetyNote": null
  },
  {
    "id": "blindfold_009",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Zoek het Attribuut",
    "text": "De ander verstopt één attribuut in de kamer. Zoek het binnen zestig seconden geblinddoekt met gesproken aanwijzingen.",
    "level": 3,
    "timerSeconds": 60,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "search"
    ],
    "safetyNote": "Blijf uit de buurt van natte vloeren, trappen en scherpe hoeken."
  },
  {
    "id": "blindfold_010",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blinde Lippenstift",
    "text": "Breng geblinddoekt lippenstift aan op de ander.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "lipstick"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_011",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Knuffelattribuut",
    "text": "Raad welk zacht attribuut of knuffeltje de ander tegen je aan houdt.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "object"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_012",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Zoete Sleutelbeenproef",
    "text": "De ander smeert een klein beetje chocoladepasta of slagroom op hals of sleutelbeen. Lik het er geblinddoekt af.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "food",
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "blindfold_013",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Aan of Uit",
    "text": "Laat je blinddoeken. De ander trekt één eenvoudig kledingstuk of accessoire uit, of doet juist iets extra’s bij je aan.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "clothing"
    ],
    "safetyNote": "Blijf zitten en kies alleen makkelijke kledingstukken of accessoires."
  },
  {
    "id": "blindfold_014",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Vind Elkaar",
    "text": "Begin allebei aan een andere kant van het bed met een blinddoek. Kruip rustig naar elkaar toe en probeer elkaar een kus te geven.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "kissing"
    ],
    "safetyNote": "Alleen op het bed uitvoeren; niet staand of op een natte vloer.",
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_015",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Koud en Warm",
    "text": "De ander beweegt kort een ijsblokje langs buik of borstkas en volgt met warme adem of zachte kusjes.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "ice",
      "kissing"
    ],
    "safetyNote": "Blijf bewegen met het ijs en gebruik het slechts enkele seconden per plek."
  },
  {
    "id": "blindfold_016",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Zoek de Aardbei",
    "text": "De ander legt een groot, zacht stukje fruit op een afgesproken plek op het lichaam. Zoek het geblinddoekt met je lippen en eet het op.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "food",
      "body-contact"
    ],
    "safetyNote": "Gebruik geen kleine harde snoepjes en blijf rechtop of halfzittend."
  },
  {
    "id": "blindfold_017",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blinde Smaaktest",
    "text": "Doe de ander een blinddoek om. Doe een kleine toef slagroom op een afgesproken plek op je lichaam. De ander zoekt die zonder handen en kust of likt hem weg.",
    "level": 3,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "food",
      "body-contact"
    ],
    "safetyNote": "Gebruik weinig slagroom, vermijd ogen en gevoelige openingen en blijf rechtop of halfzittend."
  },
  {
    "id": "blindfold_018",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blinde Tekenaar",
    "text": "De ander sluit de ogen of draagt een blinddoek. Teken met je vingertop langzaam een woord of vorm op de blote huid van de ander. Raden mag pas als je klaar bent.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "touch",
      "guessing"
    ],
    "safetyNote": "Kies alleen vooraf afgesproken plekken zoals rug, buik of bovenbeen.",
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "blindfold_019",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blinde Massage Roulette",
    "text": "Blinddoek de ander en masseer twee minuten op afgesproken plekken. Wissel onverwacht af tussen handen, lippen, haren of zachte stof. De ander raadt waarmee je aanraakt.",
    "level": 4,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "massage",
      "guessing"
    ],
    "safetyNote": "Blijf binnen afgesproken grenzen en stop direct bij WALIBI."
  },
  {
    "id": "blindfold_020",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blind Proeven: Slagroom",
    "text": "Blinddoek de ander. Doe op drie afgesproken plekken op je lichaam een klein toefje slagroom. De ander zoekt ze zonder handen en kust of likt ze weg.",
    "level": 5,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "food",
      "body-contact"
    ],
    "safetyNote": "Gebruik weinig slagroom, vermijd ogen en gevoelige openingen en blijf rechtop of halfzittend."
  },
  {
    "id": "blindfold_021",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blinde Inbraak",
    "text": "Doe een blinddoek om. De ander gaat ergens op bed of op de bank liggen. Zoek diegene op de tast en vang de ander in een stevige knuffel. Daarna mag de blinddoek af.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "search",
      "hugging"
    ],
    "safetyNote": "Alleen op bed of bank uitvoeren en rustig bewegen."
  },
  {
    "id": "blindfold_022",
    "category": "blindfold",
    "emoji": "🙈",
    "title": "Blind Vertrouwen",
    "text": "Blinddoek de ander twee minuten. Jij kiest uit kusjes, zachte aanrakingen, fluisteren of plagen op vooraf afgesproken plekken.",
    "level": 3,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "trust",
      "touch"
    ],
    "safetyNote": "Spreek grenzen vooraf af; WALIBI betekent direct stoppen."
  }
];
