export const CHAOS_CARDS = [
  {
    "id": "chaos_001",
    "category": "chaos",
    "emoji": "😂",
    "title": "Roomservice Run",
    "text": "Neem de roomservice aan terwijl je nog volledig bent opgemaakt.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "makeup",
      "roomservice"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "chaos_002",
    "category": "chaos",
    "emoji": "😂",
    "title": "Paris Fashion Week",
    "text": "Loop een catwalk alsof je op Paris Fashion Week staat.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "roleplay",
      "catwalk"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_003",
    "category": "chaos",
    "emoji": "😂",
    "title": "Haar in Handen",
    "text": "De ander mag je haar doen zoals diegene wil.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hair",
      "makeover"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_004",
    "category": "chaos",
    "emoji": "😂",
    "title": "Outfit uit de Tas",
    "text": "De ander kiest één outfit of accessoire uit de tas die jij minimaal tien minuten draagt.",
    "level": 1,
    "timerSeconds": 600,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "dressup"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_005",
    "category": "chaos",
    "emoji": "😂",
    "title": "Alleen Fluisteren",
    "text": "Je mag alleen nog fluisteren tot de volgende kaart.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "voice",
      "roleplay"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_006",
    "category": "chaos",
    "emoji": "😂",
    "title": "Persoonlijkheidswissel",
    "text": "Wissel vijf minuten van persoonlijkheid: jij speelt de ander en de ander speelt jou.",
    "level": 1,
    "timerSeconds": 300,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "roleplay"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_007",
    "category": "chaos",
    "emoji": "😂",
    "title": "Stylist voor een Halfuur",
    "text": "De ander bepaalt je outfit voor het komende halfuur met spullen die aanwezig zijn.",
    "level": 1,
    "timerSeconds": 1800,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "dressup"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_008",
    "category": "chaos",
    "emoji": "😂",
    "title": "Kledingruil",
    "text": "Ruil allebei één kledingstuk of accessoire en draag het vijftien minuten.",
    "level": 1,
    "timerSeconds": 900,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "dressup"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_009",
    "category": "chaos",
    "emoji": "😂",
    "title": "Slok en Kus",
    "text": "Eén van jullie neemt een klein slokje, zet het glas weg en geeft het drankje met een kus door. Wissel daarna. Probeer niet te knoeien.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing",
      "drink"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_010",
    "category": "chaos",
    "emoji": "😂",
    "title": "Drie Lagen Extra",
    "text": "De ander kiest drie extra kledingstukken of accessoires uit. Draag de complete combinatie twintig minuten.",
    "level": 1,
    "timerSeconds": 1200,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "dressup"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "chaos_011",
    "category": "chaos",
    "emoji": "😂",
    "title": "Blind Gestyled",
    "text": "Laat je blinddoeken. De ander krijgt twee minuten om een outfit uit de koffers te kiezen en helpt je die aantrekken. Draag hem daarna vijftien minuten.",
    "level": 1,
    "timerSeconds": 900,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "clothing",
      "dressup"
    ],
    "safetyNote": "Blijf zitten tijdens het aan- en uitkleden."
  },
  {
    "id": "chaos_012",
    "category": "chaos",
    "emoji": "😂",
    "title": "Dichterbij",
    "text": "Leg een sjaal, stropdas, panty of badjasriem losjes over de schouders van de ander en trek diegene rustig dichterbij voor een kus of knuffel.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing",
      "clothing"
    ],
    "safetyNote": "Niet om de nek leggen en trek niet hard."
  },
  {
    "id": "chaos_013",
    "category": "chaos",
    "emoji": "😂",
    "title": "Dropveterkus",
    "text": "Neem allebei één uiteinde van een aardbeiendropveter in je mond en eet naar elkaar toe zonder je handen te gebruiken. Eindig met een kus.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "food",
      "kissing"
    ],
    "safetyNote": "Doe dit rechtop en rustig om verslikken te voorkomen."
  },
  {
    "id": "chaos_014",
    "category": "chaos",
    "emoji": "😂",
    "title": "Voorwerp Versieren",
    "text": "De ander kiest een veilig voorwerp. Jij hebt dertig seconden om het zo overtuigend mogelijk te versieren alsof je ermee flirt.",
    "level": 1,
    "timerSeconds": 30,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "object",
      "roleplay",
      "flirt"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_015",
    "category": "chaos",
    "emoji": "😂",
    "title": "Emoji Uitbeelden",
    "text": "Laat de ander een emoji kiezen en speel die uit zonder uitleg.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "emoji",
      "acting",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_016",
    "category": "chaos",
    "emoji": "😂",
    "title": "Hotelober",
    "text": "Wees de komende vier kaarten de persoonlijke ober van de ander: haal drinken of snacks, ruim kleine spullen op en spreek diegene aan met meneer of mevrouw.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "roleplay",
      "service",
      "hotel"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_017",
    "category": "chaos",
    "emoji": "😂",
    "title": "Geheim Personage",
    "text": "Kies in het geheim een film-, serie- of bekend personage en beeld het zonder praten uit. De ander heeft twee minuten om te raden wie je bent.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "acting",
      "guessing",
      "roleplay"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_018",
    "category": "chaos",
    "emoji": "😂",
    "title": "Diva-Maar",
    "text": "Spreek vijf minuten lang elk woord 'maar' overdreven diva-achtig uit. Hoe dramatischer, hoe beter.",
    "level": 1,
    "timerSeconds": 300,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "voice",
      "roleplay",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_019",
    "category": "chaos",
    "emoji": "😂",
    "title": "Accent Act",
    "text": "Kies een accent en praat de komende vijf kaarten volledig met dat accent. Had je eerder een diva-opdracht, dan wordt het automatisch extra chic.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "voice",
      "roleplay",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_020",
    "category": "chaos",
    "emoji": "😂",
    "title": "Wall Sit Beloning",
    "text": "Ga in een wall sit tegen de muur zitten en houd dit zo lang mogelijk vol. De ander voert de volgende opdracht precies zo lang uit als jij volhoudt.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "physical",
      "challenge"
    ],
    "safetyNote": "Stop bij pijn of duizeligheid."
  },
  {
    "id": "chaos_021",
    "category": "chaos",
    "emoji": "😂",
    "title": "Waarheid of Leugen",
    "text": "Vertel een absurd verhaal dat echt of verzonnen kan zijn. De ander raadt daarna: waarheid of leugen.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "story",
      "guessing",
      "conversation"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_022",
    "category": "chaos",
    "emoji": "😂",
    "title": "AI-Achtergrond",
    "text": "Laat de ander een AI-achtergrond voor je telefoon bedenken en genereren. Gebruik die tot het einde van de date.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "phone",
      "creative",
      "ai"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_023",
    "category": "chaos",
    "emoji": "😂",
    "title": "Buikspreker",
    "text": "Jij bent de buikspreker. Doe de mondbewegingen van de ander zo goed mogelijk na zonder zelf geluid te maken.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "acting",
      "voice",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_024",
    "category": "chaos",
    "emoji": "😂",
    "title": "Moonwalk Score",
    "text": "Doe je beste moonwalk door de kamer. De ander geeft daarna een cijfer van 1 tot 10.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": "vrouw",
    "contentTags": [
      "dance",
      "rating",
      "humor"
    ],
    "safetyNote": "Doe dit alleen op een droge vloer met genoeg ruimte."
  },
  {
    "id": "chaos_025",
    "category": "chaos",
    "emoji": "😂",
    "title": "Advocaat van de Duivel",
    "text": "De ander bedenkt een absurde stelling die bijna niet te verdedigen is. Jij krijgt dertig seconden om die zo overtuigend mogelijk te verdedigen.",
    "level": 1,
    "timerSeconds": 30,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "debate",
      "roleplay",
      "humor"
    ],
    "safetyNote": "Houd het speels en respectvol."
  },
  {
    "id": "chaos_026",
    "category": "chaos",
    "emoji": "😂",
    "title": "Dierengeluid",
    "text": "Kies een dier en doe het geluid zo overtuigend mogelijk na.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "acting",
      "sound",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_027",
    "category": "chaos",
    "emoji": "😂",
    "title": "Sales Pitch",
    "text": "Je hebt vijftien seconden om jezelf te verkopen alsof je een exclusief nieuw product bent.",
    "level": 1,
    "timerSeconds": 15,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "pitch",
      "conversation",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_028",
    "category": "chaos",
    "emoji": "😂",
    "title": "Kabouterdans",
    "text": "Doe de kabouterdans zo goed mogelijk na.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": "vrouw",
    "contentTags": [
      "dance",
      "humor"
    ],
    "safetyNote": "Alleen op een droge vloer met genoeg ruimte."
  },
  {
    "id": "chaos_029",
    "category": "chaos",
    "emoji": "😂",
    "title": "Dramatische Quote",
    "text": "Lees of verzin een Twilight-achtige quote en breng die zo serieus en dramatisch mogelijk.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "quote",
      "drama",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "chaos_030",
    "category": "chaos",
    "emoji": "😂",
    "title": "Kledingruil Twist",
    "text": "Kies één kledingstuk of accessoire dat je nu draagt en trek het zo theatraal mogelijk uit. De ander draagt het tot de volgende kaart bovenop de eigen outfit.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "dressup",
      "roleplay"
    ],
    "safetyNote": "Kies iets dat makkelijk en veilig over de eigen outfit gedragen kan worden.",
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "chaos_031",
    "category": "chaos",
    "emoji": "😂",
    "title": "Kleding-Kakofonie",
    "text": "Kies één fout of opvallend kledingstuk van jezelf. De ander trekt het nu bovenop de eigen outfit aan en houdt het drie speelrondes aan.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "dressup",
      "humor"
    ],
    "safetyNote": "Alleen kleding die comfortabel en veilig over de outfit past."
  },
  {
    "id": "chaos_032",
    "category": "chaos",
    "emoji": "😂",
    "title": "De Nee-Ronde",
    "text": "Speel twee minuten alsof het antwoord op elke speelse vraag alleen maar 'nee' mag zijn. De vragensteller probeert de ander uit de rol te krijgen zonder echte grenzen te pushen.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "roleplay",
      "conversation",
      "humor"
    ],
    "safetyNote": "Een echt nee blijft altijd nee; houd het spel luchtig."
  },
  {
    "id": "chaos_034",
    "category": "chaos",
    "emoji": "😂",
    "title": "Steen-Papier-Schaar Straf",
    "text": "Speel één potje steen-papier-schaar. De winnaar krijgt vijftien seconden om de verliezer speels te kietelen in de nek of zij.",
    "level": 4,
    "timerSeconds": 15,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "game",
      "tickling",
      "humor"
    ],
    "safetyNote": "Stop meteen als iemand wegtrekt of WALIBI zegt."
  }
];
