export const CUTE_CARDS = [
  {
    "id": "cute_001",
    "category": "cute",
    "emoji": "❤️",
    "title": "Twintig Gezichtskusjes",
    "text": "Geef elkaar twintig kusjes op het gezicht.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_002",
    "category": "cute",
    "emoji": "❤️",
    "title": "Stille Knuffel",
    "text": "Knuffel elkaar twee minuten zonder te praten.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hugging"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_003",
    "category": "cute",
    "emoji": "❤️",
    "title": "Zestig Seconden Kijken",
    "text": "Kijk elkaar zestig seconden aan.",
    "level": 1,
    "timerSeconds": 60,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "eye-contact"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_004",
    "category": "cute",
    "emoji": "❤️",
    "title": "Drie Mooie Dingen",
    "text": "Vertel drie dingen die je leuk vindt aan de ander.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_005",
    "category": "cute",
    "emoji": "❤️",
    "title": "Dans in Volle Overgave",
    "text": "Dans in volle overgave voor de ander.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": "vrouw",
    "contentTags": [
      "dance"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_006",
    "category": "cute",
    "emoji": "❤️",
    "title": "Voer Mij",
    "text": "Voer elkaar iets lekkers.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "food"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_007",
    "category": "cute",
    "emoji": "❤️",
    "title": "Filmknuffel",
    "text": "Geef elkaar drie minuten een overdreven romantische filmknuffel.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hugging",
      "roleplay"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_008",
    "category": "cute",
    "emoji": "❤️",
    "title": "Briefje in Zestig Seconden",
    "text": "Schrijf in zestig seconden een lief briefje voor elkaar.",
    "level": 1,
    "timerSeconds": 60,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "writing"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_009",
    "category": "cute",
    "emoji": "❤️",
    "title": "Knuffel tot de Lach",
    "text": "Knuffel elkaar tot iemand moet lachen.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hugging"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_010",
    "category": "cute",
    "emoji": "❤️",
    "title": "Bucketlist voor Later",
    "text": "Bedenk samen één ding dat jullie ooit samen willen doen.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation",
      "future"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_011",
    "category": "cute",
    "emoji": "❤️",
    "title": "Favoriete Date",
    "text": "Vertel wat je leukste date tot nu toe vond.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "cute_012",
    "category": "cute",
    "emoji": "❤️",
    "title": "Samen uit het Raam",
    "text": "Kijk twee minuten samen stil uit het raam.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "quiet"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "cute_013",
    "category": "cute",
    "emoji": "❤️",
    "title": "Nieuwe Traditie",
    "text": "Bedenk samen een kleine traditie voor toekomstige dates.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation",
      "future"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_014",
    "category": "cute",
    "emoji": "❤️",
    "title": "Hotelshop Missie",
    "text": "Ga naar het hotelwinkeltje en koop iets lekkers. De ander heeft ondertussen even tijd voor zichzelf of om zich om te kleden.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": "man",
    "contentTags": [
      "shopping",
      "food"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_015",
    "category": "cute",
    "emoji": "❤️",
    "title": "Attribuut Anders Gebruiken",
    "text": "Pak een attribuut en gebruik het op een veilige, grappige manier waarvoor het niet bedoeld is.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "object",
      "creative"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "cute_016",
    "category": "cute",
    "emoji": "❤️",
    "title": "Openen in Zweden",
    "text": "Schrijf een lief berichtje dat de ander pas mag openen wanneer Winnie in Zweden is.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "writing",
      "future"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_017",
    "category": "cute",
    "emoji": "❤️",
    "title": "Bodylotionmoment",
    "text": "Ga comfortabel liggen. De ander brengt rustig verzorgende crème of bodylotion aan op armen, benen, rug of schouders.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "lotion",
      "massage"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_018",
    "category": "cute",
    "emoji": "❤️",
    "title": "Handmassage",
    "text": "Masseer langzaam elke vinger en de handpalm van de ander met een beetje lotion terwijl jullie elkaar aankijken.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "massage",
      "lotion",
      "eye-contact"
    ],
    "safetyNote": null,
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "cute_019",
    "category": "cute",
    "emoji": "❤️",
    "title": "Chocoladelippen",
    "text": "Smeer een dun streepje chocoladepasta op de lippen van de ander en kus het er langzaam af.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "food",
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_020",
    "category": "cute",
    "emoji": "❤️",
    "title": "Trots Geheim",
    "text": "Vertel een klein geheim, gênante gewoonte of iets waar je je stiekem voor schaamt, maar doe alsof je er trots op bent.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation",
      "secret",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_021",
    "category": "cute",
    "emoji": "❤️",
    "title": "Laatste Nummer",
    "text": "Laat de ander je laatst afgespeelde nummer horen en vertel waarom het bij jou past.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "music",
      "conversation",
      "phone"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_022",
    "category": "cute",
    "emoji": "❤️",
    "title": "Beste Vriend(in)",
    "text": "Praat één minuut over de ander alsof je bij je beste vriend(in) aan het roddelen bent. Houd het lief genoeg om samen om te lachen.",
    "level": 1,
    "timerSeconds": 60,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation",
      "humor"
    ],
    "safetyNote": null
  },
  {
    "id": "cute_023",
    "category": "cute",
    "emoji": "❤️",
    "title": "Droomteam",
    "text": "Stel een team van vijf personen samen dat elke missie zou winnen. Leg per persoon kort uit welke rol diegene krijgt.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "conversation",
      "team",
      "humor"
    ],
    "safetyNote": null
  }
];
