export const JACUZZI_CARDS = [
  {
    "id": "jacuzzi_fun_001",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Schuimbaard",
    "text": "Maak een schuimbaard bij de ander.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "foam"
    ],
    "safetyNote": null,
    "intensity": "fun",
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "jacuzzi_fun_002",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Schuimkapsel",
    "text": "Maak een schuimkapsel bij de ander.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "foam"
    ],
    "safetyNote": null,
    "intensity": "fun",
    "enabled": false,
    "disabledReason": "Tijdelijk uitgezet op 2026-08-12 na PDF-review; bewaren voor mogelijke heractivatie."
  },
  {
    "id": "jacuzzi_fun_003",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Bovenwaterkus",
    "text": "Houd allebei kort je adem in, kom tegelijk boven water en geef elkaar direct een kus.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing"
    ],
    "safetyNote": "Niet onder water zoenen.",
    "intensity": "fun"
  },
  {
    "id": "jacuzzi_fun_004",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Koude Verrassing",
    "text": "Giet een klein beetje koud water in de nek of op de rug van de ander terwijl die in het warme water zit.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "cold"
    ],
    "safetyNote": "Gebruik geen ijskoud water op het gezicht of beschadigde huid.",
    "intensity": "fun"
  },
  {
    "id": "jacuzzi_cute_001",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Tegen Elkaar Aan",
    "text": "Leun drie minuten tegen elkaar aan.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "hugging"
    ],
    "safetyNote": null,
    "intensity": "cute"
  },
  {
    "id": "jacuzzi_cute_002",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Twintig Waterkusjes",
    "text": "Geef elkaar twintig kusjes terwijl jullie in het water blijven.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing"
    ],
    "safetyNote": null,
    "intensity": "cute"
  },
  {
    "id": "jacuzzi_cute_003",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Bubbels en Ogen Dicht",
    "text": "Sluit je ogen en geniet twee minuten samen van de bubbels.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "relax"
    ],
    "safetyNote": null,
    "intensity": "cute"
  },
  {
    "id": "jacuzzi_cute_004",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Schoudermassage",
    "text": "Geef elkaar een rustige schoudermassage.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "massage"
    ],
    "safetyNote": null,
    "intensity": "cute"
  },
  {
    "id": "jacuzzi_flirty_001",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Drie Minuten Kusmarathon",
    "text": "Zoen elkaar drie minuten terwijl de bubbels aanstaan.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing"
    ],
    "safetyNote": null,
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_002",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Handenvrije Waterkus",
    "text": "Geef elkaar kusjes zonder je handen te gebruiken.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing"
    ],
    "safetyNote": null,
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_003",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Ogen Dicht, Verrassing",
    "text": "Sluit je ogen. De ander verrast je met een kus of knuffel.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing",
      "hugging"
    ],
    "safetyNote": null,
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_004",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Zit zoals Ik Wil",
    "text": "De ander bepaalt hoe jullie de komende drie minuten zitten.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "body-contact"
    ],
    "safetyNote": null,
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_005",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Langzaam Dichterbij",
    "text": "De ander mag je langzaam dichterbij trekken.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "body-contact"
    ],
    "safetyNote": null,
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_006",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Niet Wegkijken",
    "text": "Zoen elkaar en kijk tussendoor in elkaars ogen. Wie als eerste wegkijkt, krijgt later een lippenstiftkus.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing",
      "eye-contact"
    ],
    "safetyNote": null,
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_007",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Koude Kus",
    "text": "Neem een klein slokje koud water, slik het door en geef de ander direct daarna een lange kus.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "kissing",
      "cold"
    ],
    "safetyNote": "Slik eerst door voordat jullie zoenen.",
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_flirty_008",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Onderwaterkietel",
    "text": "Kietel de ander maximaal één minuut onder water bij de zij of knieën.",
    "level": 1,
    "timerSeconds": 60,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "tickling"
    ],
    "safetyNote": "Stop direct bij WALIBI en houd het gezicht boven water.",
    "intensity": "flirty"
  },
  {
    "id": "jacuzzi_oohlala_001",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Drie Minuten Stil",
    "text": "Jullie mogen de komende drie minuten niet praten.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "silence"
    ],
    "safetyNote": null,
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_002",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Rug- of Schoudermassage",
    "text": "De ander masseert drie minuten je rug of schouders.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "massage"
    ],
    "safetyNote": null,
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_003",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Benen en Voeten",
    "text": "Masseer twee minuten de benen en voeten van de ander onder water.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "massage",
      "feet"
    ],
    "safetyNote": null,
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_004",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Gewaagde Fluistering",
    "text": "Fluister een gewaagde fantasie voor deze avond in het oor van de ander terwijl je zachte kusjes in de nek geeft.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "whisper",
      "kissing"
    ],
    "safetyNote": null,
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_005",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Langs de Rug",
    "text": "Ga achter de ander zitten en ga met een natte vinger langzaam langs de ruggengraat omhoog tot in de nek. Eindig met een zachte kus bij het oor.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "touch",
      "kissing"
    ],
    "safetyNote": null,
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_006",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Rand van de Zwemkleding",
    "text": "De ander mag één minuut langs de rand van je zwemkleding en over aangrenzende huid strelen, binnen vooraf afgesproken grenzen.",
    "level": 1,
    "timerSeconds": 60,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "touch",
      "swimwear"
    ],
    "safetyNote": "Niet onder de zwemkleding zonder een duidelijke, actuele ja.",
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_007",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Kietelen tijdens het Zoenen",
    "text": "De ander kietelt zachtjes in je zij terwijl jullie zoenen. Laat je los om te lachen, dan krijg je later een lippenstiftkus.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "tickling",
      "kissing"
    ],
    "safetyNote": "Houd het gezicht boven water en stop direct bij WALIBI.",
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_008",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Voeten en Benen",
    "text": "De ander mag twee minuten met voeten en benen langs jouw benen en dijen bewegen terwijl jullie elkaar aankijken.",
    "level": 1,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "feet",
      "legs",
      "eye-contact"
    ],
    "safetyNote": null,
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_oohlala_009",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Jacuzzi Freeze",
    "text": "Ga dicht tegen elkaar aan zitten. Eén van jullie laat een ijsblokje onder water langzaam over rug of benen van de ander glijden totdat het smelt.",
    "level": 5,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "ice",
      "temperature",
      "touch"
    ],
    "safetyNote": "Houd gezichten boven water, blijf bewegen met het ijs en stop direct bij WALIBI.",
    "intensity": "oohlala"
  },
  {
    "id": "jacuzzi_special_001",
    "category": "jacuzzi",
    "emoji": "🛁",
    "title": "Wellness of Chaos",
    "text": "Kies: twee minuten ontspannen genieten óf trek direct drie Flirty- of Oohlala-kaarten die geschikt zijn voor de jacuzzi.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": "wellnessOrChaos",
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "special"
    ],
    "safetyNote": null,
    "intensity": "fun"
  },
  {
    "id": "jacuzzi_bubble_001",
    "category": "jacuzzi",
    "emoji": "🫧",
    "title": "Extra Bubbels",
    "text": "Zet de bubbels op maximaal.",
    "level": 1,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": "bubbleExtra",
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "bubble"
    ],
    "safetyNote": null,
    "intensity": "fun"
  },
  {
    "id": "jacuzzi_bubble_002",
    "category": "jacuzzi",
    "emoji": "🫧",
    "title": "Koud Water",
    "text": "Zet maximaal tien seconden een klein straaltje koel water aan.",
    "level": 1,
    "timerSeconds": 10,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": "bubbleCold",
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "cold"
    ],
    "safetyNote": "Gebruik geen extreem koud water en richt niet op het gezicht.",
    "intensity": "fun"
  },
  {
    "id": "jacuzzi_bubble_003",
    "category": "jacuzzi",
    "emoji": "🫧",
    "title": "Wellnesspauze",
    "text": "Drie minuten geen opdrachten. Gewoon samen genieten.",
    "level": 1,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": true,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": "bubbleWellness",
    "playerRestriction": null,
    "contentTags": [
      "jacuzzi",
      "relax"
    ],
    "safetyNote": null,
    "intensity": "cute"
  }
];
