export const OOHLALA_CARDS = [
  {
    "id": "oohlala_001",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Twee Minuten Kusregie",
    "text": "De ander bepaalt twee minuten waar jij kusjes geeft, binnen jullie afgesproken grenzen.",
    "level": 4,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": "De ander kiest drie kusplekken boven de schouders.",
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_002",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Handen Geleid",
    "text": "De ander mag je handen twee minuten begeleiden naar afgesproken plekken waar diegene graag wordt aangeraakt.",
    "level": 4,
    "timerSeconds": 120,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hands",
      "touch"
    ],
    "safetyNote": "WALIBI betekent direct stoppen."
  },
  {
    "id": "oohlala_003",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Drie Minuten Knuffelregie",
    "text": "De ander bepaalt drie minuten hoe jullie knuffelen.",
    "level": 5,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hugging"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_004",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Eén Laag Minder",
    "text": "Trek één kledingstuk of accessoire uit, bijvoorbeeld schoenen, badjas, trui of sokken.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_005",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Langzaam Begeleiden",
    "text": "De ander mag je hand langzaam begeleiden naar een afgesproken plek waar diegene graag wordt aangeraakt.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hands",
      "touch"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_006",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Kus Terug",
    "text": "De ander geeft jou ergens een kus. Daarna geef jij op dezelfde plek een kus terug.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_007",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Massage met Kusjes",
    "text": "Geef drie minuten een sensuele massage op een afgesproken lichaamsdeel met zachte kusjes en aanrakingen.",
    "level": 4,
    "timerSeconds": 180,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "massage",
      "kissing"
    ],
    "safetyNote": "Vermijd ogen, oren en andere gevoelige openingen."
  },
  {
    "id": "oohlala_008",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Langzaam Uit",
    "text": "Trek heel langzaam één kledingstuk uit terwijl je de ander blijft aankijken.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "eye-contact"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_009",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Stil Ontvangen",
    "text": "De ander masseert en plaagt je drie minuten op afgesproken plekken. Jij blijft stil en raakt de ander niet aan.",
    "level": 4,
    "timerSeconds": 180,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "massage",
      "touch"
    ],
    "safetyNote": "WALIBI betekent direct stoppen."
  },
  {
    "id": "oohlala_010",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Losse Polsen",
    "text": "De ander houdt je polsen drie minuten losjes bij elkaar met een badjasriem, stropdas, panty of sjaal en kiest uit kusjes, knuffelen of zachte aanrakingen.",
    "level": 4,
    "timerSeconds": 180,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "restraint",
      "kissing",
      "touch"
    ],
    "safetyNote": "Niet vastmaken aan meubels; er moeten twee vingers tussen passen; direct los bij WALIBI."
  },
  {
    "id": "oohlala_011",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Voetenkietel",
    "text": "De ander bindt je enkels losjes vast en kietelt je maximaal dertig seconden onder je voeten. Stopwoord: WALIBI.",
    "level": 5,
    "timerSeconds": 30,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "feet",
      "tickling"
    ],
    "safetyNote": "Alleen met iets dat direct los kan. Stop meteen bij WALIBI."
  },
  {
    "id": "oohlala_012",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Lapdance",
    "text": "Geef de ander een speelse lapdance van maximaal twee minuten.",
    "level": 4,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": "vrouw",
    "contentTags": [
      "dance",
      "lap"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_013",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Donkere Knuffel",
    "text": "Dim de lichten en knuffel en kus vijf minuten samen op bed.",
    "level": 4,
    "timerSeconds": 300,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "dark",
      "hugging",
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_014",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Polsen Vast",
    "text": "Laat de ander je polsen drie minuten losjes bij elkaar houden met een panty, stropdas of badjasriem en kiezen uit zachte kusjes, knuffelen of aanrakingen.",
    "level": 4,
    "timerSeconds": 180,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "panty",
      "restraint",
      "touch"
    ],
    "safetyNote": "Niet vastmaken aan meubels; direct los bij WALIBI."
  },
  {
    "id": "oohlala_015",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Panty Langzaam Uit",
    "text": "De ander trekt je panty in minimaal twee minuten langzaam uit en geeft onderweg zachte kusjes op de huid die vrijkomt.",
    "level": 4,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "panty",
      "clothing",
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_016",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Zoete Plek",
    "text": "Leg een beetje slagroom, chocoladepasta of een aardbei op nek, sleutelbeen of buik en eet of kus het er zonder handen af.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "food",
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_017",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Chocoladelijn",
    "text": "Teken een dunne lijn chocoladepasta van hals via borstkas naar navel en kus of lik die langzaam weg.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "food",
      "kissing"
    ],
    "safetyNote": null
  },
  {
    "id": "oohlala_018",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Geblinddoekt Ontvangen",
    "text": "Draag twee minuten een blinddoek terwijl de ander kiest uit zachte aanrakingen, kusjes of knuffelen op vooraf afgesproken plekken.",
    "level": 4,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "blindfold",
      "touch",
      "kissing"
    ],
    "safetyNote": "WALIBI betekent direct stoppen."
  },
  {
    "id": "oohlala_019",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Eén Lange Lijn",
    "text": "De ander trekt langzaam met vingertoppen één lijn van je voet langs de buiten- of voorkant van je been, over je buik, tot aan je lippen. Blijf zo stil mogelijk liggen.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "touch",
      "feet"
    ],
    "safetyNote": "Vermijd de binnenkant van de bovenbenen als dat niet vooraf is afgesproken."
  },
  {
    "id": "oohlala_020",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Slagroom-Kus",
    "text": "Neem allebei een kleine hap slagroom in je mond en geef elkaar een lange, romige kus voordat jullie doorslikken.",
    "level": 4,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "food",
      "kissing"
    ],
    "safetyNote": "Gebruik weinig slagroom, blijf rechtop zitten en stop meteen bij hoesten of verslikken."
  },
  {
    "id": "oohlala_021",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Temperatuur Schok",
    "text": "Maak je vingers koel onder de kraan of juist warm met warm water. Glijd daarna zestig seconden langzaam onder het shirt van de ander over rug, buik of zij.",
    "level": 4,
    "timerSeconds": 60,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "temperature",
      "touch",
      "clothing"
    ],
    "safetyNote": "Test de temperatuur eerst op jezelf en gebruik niets extreems."
  },
  {
    "id": "oohlala_022",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Stropdas Gijzeling",
    "text": "Gebruik een stropdas of sjaal zodat de ander de handen losjes achter de rug houdt. Jij leidt de opdracht en geeft drie intense, plagerige kusjes op plekken naar keuze, behalve op de mond.",
    "level": 5,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "restraint",
      "kissing",
      "teasing"
    ],
    "safetyNote": "Niet knopen of vastmaken; direct los bij WALIBI."
  },
  {
    "id": "oohlala_023",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Knopen Koning",
    "text": "Kies een kledingstuk met knopen of een rits bij de ander. Open het binnen negentig seconden met alleen je tanden, terwijl je handen op je eigen rug blijven.",
    "level": 4,
    "timerSeconds": 90,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "challenge",
      "teeth"
    ],
    "safetyNote": "Doe rustig en blijf weg van huid, haar en sieraden."
  },
  {
    "id": "oohlala_024",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Handen Thuis",
    "text": "Leg de handen van de ander plat op tafel of bed. De ander laat ze daar twee minuten liggen terwijl jij kust en aanraakt op vooraf afgesproken plekken. Verplaatst de ander de handen, dan stopt de beurt.",
    "level": 5,
    "timerSeconds": 120,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "hands",
      "touch",
      "kissing"
    ],
    "safetyNote": "WALIBI betekent direct stoppen."
  },
  {
    "id": "oohlala_025",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Slow-Motion Kus",
    "text": "Zoen elkaar één minuut in extreme slow-motion. Elke beweging gaat overdreven langzaam, zonder tussendoor te versnellen.",
    "level": 5,
    "timerSeconds": 60,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing",
      "slow"
    ],
    "safetyNote": "Blijf rustig ademen en stop bij ongemak."
  },
  {
    "id": "oohlala_026",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Ultieme Keuze",
    "text": "Kies je dilemma: trek nu twee kledingstukken of accessoires van jezelf uit, óf laat de ander jou blinddoeken en twee minuten plagen op afgesproken plekken.",
    "level": 5,
    "timerSeconds": null,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "choice",
      "clothing",
      "blindfold"
    ],
    "safetyNote": "Kies alleen wat binnen jullie grenzen past; WALIBI stopt alles."
  },
  {
    "id": "oohlala_027",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Geluidsbarrière",
    "text": "Plaag en kus de ander één minuut op afgesproken gevoelige plekken. De ander blijft muisstil. Maakt diegene toch geluid, voeg dan dertig seconden toe.",
    "level": 5,
    "timerSeconds": 60,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "teasing",
      "kissing",
      "silence"
    ],
    "safetyNote": "Alleen op afgesproken plekken en stop direct bij WALIBI."
  },
  {
    "id": "oohlala_028",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Bijna-Kus Boete",
    "text": "Maak de ander één minuut gek door heel dichtbij te komen, de hals te kussen en te knuffelen. Probeert de ander jou op de mond te kussen, trek je lachend terug.",
    "level": 4,
    "timerSeconds": 60,
    "jacuzziAllowed": true,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "kissing",
      "teasing",
      "hugging"
    ],
    "safetyNote": "Houd het speels en stop bij WALIBI."
  },
  {
    "id": "oohlala_029",
    "category": "oohlala",
    "emoji": "🔥",
    "title": "Kleding-Wissel",
    "text": "Je krijgt zestig seconden om één kledingstuk of accessoire van jezelf uit te trekken en bij de ander aan te trekken. De ander helpt, maar mag alleen de tanden gebruiken om stof vast te pakken.",
    "level": 4,
    "timerSeconds": 60,
    "jacuzziAllowed": false,
    "requiresJacuzzi": false,
    "repeatable": false,
    "upgradeText": null,
    "lighterText": null,
    "specialType": null,
    "playerRestriction": null,
    "contentTags": [
      "clothing",
      "challenge",
      "teeth"
    ],
    "safetyNote": "Niet trekken aan huid, haar, sieraden of kwetsbare stof."
  }
];
